SET_TABLE_DIM = "SET_TABLE_DIM"
SET_POT = "SET_POT"
SET_SEATS = "SET_SEATS"
SET_BOARD = "SET_BOARD"
SET_ACTIVE_TAB = "SET_ACTIVE_TAB"
SET_DEALER = "SET_DEALER"

# Review actions
SET_REVIEW_HANDS = "SET_REVIEW_HANDS"
SET_REVIEW_FILTER = "SET_REVIEW_FILTER"
SET_LOADED_HAND = "SET_LOADED_HAND"
SET_STUDY_MODE = "SET_STUDY_MODE"
SET_REVIEW_COLLECTION = "SET_REVIEW_COLLECTION"

# Enhanced RPGW actions for Hands Review Session
ENHANCED_RPGW_EXECUTE_ACTION = "ENHANCED_RPGW_EXECUTE_ACTION"
UPDATE_ENHANCED_RPGW_STATE = "UPDATE_ENHANCED_RPGW_STATE"
ENHANCED_RPGW_ANIMATION_EVENT = "ENHANCED_RPGW_ANIMATION_EVENT"

# Hands Review Session specific actions
LOAD_REVIEW_HAND = "LOAD_REVIEW_HAND"
NEXT_REVIEW_ACTION = "NEXT_REVIEW_ACTION"
PREV_REVIEW_ACTION = "PREV_REVIEW_ACTION"
RESET_REVIEW_HAND = "RESET_REVIEW_HAND"
SET_REVIEW_PROGRESS = "SET_REVIEW_PROGRESS"
SET_REVIEW_STATUS = "SET_REVIEW_STATUS"

# Architecture compliant action for hands review
HANDS_REVIEW_NEXT_ACTION = "HANDS_REVIEW_NEXT_ACTION"


