SET_TABLE_DIM = "SET_TABLE_DIM"
SET_POT = "SET_POT"
SET_SEATS = "SET_SEATS"
SET_BOARD = "SET_BOARD"
SET_ACTIVE_TAB = "SET_ACTIVE_TAB"
SET_DEALER = "SET_DEALER"

# Review actions
SET_REVIEW_HANDS = "SET_REVIEW_HANDS"
SET_REVIEW_FILTER = "SET_REVIEW_FILTER"
SET_LOADED_HAND = "SET_LOADED_HAND"
SET_STUDY_MODE = "SET_STUDY_MODE"
SET_REVIEW_COLLECTION = "SET_REVIEW_COLLECTION"


